apiVersion: apps/v1
kind: Deployment
metadata:
  name: "goserver"
  labels:
    app: "goserver"
spec:
  selector:
    matchLabels:
      app: "goserver"
  replicas: 2
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
       - name: "goserver"
         image: "mgsantos89/hello-go:latest"
         #Add Env hardcoded Direto no Deployment
         #env:
         # - name: NAME
         #   value: "Marco Gomes"
         # - name: AGE 
         #   value: "35"
         ##########
         #Add Env. Coletada do Configmap
         #Uma a Uma
         #env: 
         # - name: NAME
         #   valueFrom:
         #     configMapKeyRef:
         #       name: goserver-env
         #       key: NAME
         # - name: AGE
         #   valueFrom:
         #     configMapKeyRef:
         #       name: goserver-env
         #       key: AGE
         ############
         #Add EndFrom e carregar todas as variaveis do Configmap
         envFrom:
          - configMapRef:
              name: goserver-env
        #Montando um volume
         volumeMounts:
           - name:  "/go/myfamily"
             mountPath:  config
      #Declarando volume com dados do confimap
      volumes:
        - name: configmap
          configMap: 
            name: configmap-family
            items: 
            - key: members
              path: "family.txt"
