apiVersion: apps/v1
kind: Deployment
metadata:
  name: "goserver"
  labels:
    app: "goserver"
spec:
  selector:
    matchLabels:
      app: "goserver"
  replicas: 2
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
       - name: "goserver"
         image: "mgsantos89/hello-go:latest"
         #Add Env hardcoded Direto no Deployment
         #env:
         # - name: NAME
         #   value: "Marco Gomes"
         # - name: AGE 
         #   value: "35"
         ##########
         #Add Env. Coletada do Configmap
         env: 
          - name: NAME
            valueFrom:
              configMapKeyRef:
                name: goserver-env
                key: NAME
          - name: AGE
            valueFrom:
              configMapKeyRef:
                name: goserver-env
                key: AGE