apiVersion: apps/v1
kind: Deployment
metadata:
  name: "goserver"
  labels:
    app: "goserver"
spec:
  selector:
    matchLabels:
      app: "goserver"
  replicas: 2
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
       - name: "goserver"
         image: "mgsantos89/hello-go:latest"
         #Add Env
         env:
          - name: NAME
            value: "Marco Gomes"
          - name: AGE 
            value: "35"